version: "3"

services:
  notebook:
    container_name: jupyter_notebook
    build:
      context: .
      dockerfile: Dockerfile_Python_Jupyter
    volumes:
      - ./:/workspace
    ports:
      - 80:8888
    command: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root